#!/bin/sh
set -eu

export PGPASSWORD="${FASTORDER_POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 -h 127.0.0.1 -U postgres -d postgres <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${FASTORDER_APP_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${FASTORDER_APP_USER}', '${FASTORDER_APP_PASSWORD}');
    ELSE
        EXECUTE format('ALTER ROLE %I WITH LOGIN PASSWORD %L', '${FASTORDER_APP_USER}', '${FASTORDER_APP_PASSWORD}');
    END IF;
END
\$\$;

SELECT format('CREATE DATABASE %I OWNER %I', '${FASTORDER_APP_DB}', '${FASTORDER_APP_USER}')
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${FASTORDER_APP_DB}')
\gexec

GRANT ALL PRIVILEGES ON DATABASE ${FASTORDER_APP_DB} TO ${FASTORDER_APP_USER};
SQL

export PGPASSWORD="${FASTORDER_APP_PASSWORD}"

psql -v ON_ERROR_STOP=1 -h 127.0.0.1 -U "${FASTORDER_APP_USER}" -d "${FASTORDER_APP_DB}" -f /bootstrap/fastorder-init.sql

export PGPASSWORD="${FASTORDER_POSTGRES_PASSWORD}"

psql -v ON_ERROR_STOP=1 -h 127.0.0.1 -U postgres -d "${FASTORDER_APP_DB}" <<SQL
ALTER SCHEMA public OWNER TO ${FASTORDER_APP_USER};
GRANT ALL ON SCHEMA public TO ${FASTORDER_APP_USER};
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${FASTORDER_APP_USER};
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${FASTORDER_APP_USER};
ALTER DEFAULT PRIVILEGES FOR USER ${FASTORDER_APP_USER} IN SCHEMA public GRANT ALL ON TABLES TO ${FASTORDER_APP_USER};
ALTER DEFAULT PRIVILEGES FOR USER ${FASTORDER_APP_USER} IN SCHEMA public GRANT ALL ON SEQUENCES TO ${FASTORDER_APP_USER};
SQL
