services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fastorder-rabbitmq-pc4
    hostname: ${RABBITMQ_NODE_3_NAME}
    environment:
      RABBITMQ_NODENAME: rabbit@${RABBITMQ_NODE_3_NAME}
      RABBITMQ_USE_LONGNAME: "false"
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    volumes:
      - rabbitmq_pc4_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    ports:
      - "5672:5672"
      - "15672:15672"
      - "25672:25672"
      - "4369:4369"
    extra_hosts:
      - "${RABBITMQ_NODE_1_NAME}:${RABBITMQ_NODE_1_IP}"
      - "${RABBITMQ_NODE_2_NAME}:${RABBITMQ_NODE_2_IP}"
      - "${RABBITMQ_NODE_3_NAME}:${RABBITMQ_NODE_3_IP}"
    restart: unless-stopped

volumes:
  rabbitmq_pc4_data:
