server:
  port: 8084

spring:
  application:
    name: kitchen-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5440/fastorder_db}
    username: ${SPRING_DATASOURCE_USERNAME:fastorder_user}
    password: ${SPRING_DATASOURCE_PASSWORD:fastorder123}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

app:
  services:
    order-url: ${ORDER_SERVICE_URL:http://localhost:8082/orders}
  rabbit:
    exchange: kitchen.exchange
    queue: kitchen.events.queue
    routing-key: kitchen.event
