global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: docker-stats
    static_configs:
      - targets:
          - docker-stats-exporter:9104

  - job_name: rabbitmq
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: rabbitmq-per-object
    metrics_path: /metrics/per-object
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: postgres-primary
    static_configs:
      - targets:
          - postgres-exporter-db-0:9187

  - job_name: postgres-replica
    static_configs:
      - targets:
          - postgres-exporter-db-1:9187
          - postgres-exporter-db-2:9187

  - job_name: postgres-proxy
    static_configs:
      - targets:
          - postgres-exporter-db-proxy:9187

  - job_name: api-gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - api-gateway:8080

  - job_name: menu-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - menu-service:8081

  - job_name: order-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - order-service:8082

  - job_name: inventory-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - inventory-service:8083

  - job_name: kitchen-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - kitchen-service:8084

  - job_name: delivery-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - delivery-service:8085

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - notification-service:8086
