spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5440}/${DB_NAME:fastorder_db}
    username: ${DB_USER:fastorder_user}
    password: ${DB_PASSWORD:fastorder123}
    driver-class-name: org.postgresql.Driver

  application:
    name: menu-service

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: menu-service
    description: Microservicio de administracion y consulta de productos del menu para FastOrder HA
    version: 0.0.1-SNAPSHOT

app:
  rabbit:
    exchange: menu.exchange
    queue: menu.events.queue
    routing-key: menu.event

logging:
  level:
    root: INFO
    com.fastorder.menu: DEBUG
